data = [
    {"name": "Instagram", "follower_count": 694, "description": "Social media platform", "country": "United States"},
    {"name": "Cristiano Ronaldo", "follower_count": 663, "description": "Footballer", "country": "Portugal"},
    {"name": "Lionel Messi", "follower_count": 506, "description": "Footballer", "country": "Argentina"},
    {"name": "Selena Gomez", "follower_count": 418, "description": "Musician & actress", "country": "United States"},
    {"name": "Kylie Jenner", "follower_count": 393, "description": "Media personality", "country": "United States"},
    {"name": "Dwayne Johnson", "follower_count": 393, "description": "Actor & wrestler", "country": "United States"},
    {"name": "Ariana Grande", "follower_count": 374, "description": "Musician & actress", "country": "United States"},
    {"name": "Kim Kardashian", "follower_count": 356, "description": "Media personality", "country": "United States"},
    {"name": "Beyoncé", "follower_count": 310, "description": "Musician & actress", "country": "United States"},
    {"name": "Khloé Kardashian", "follower_count": 302, "description": "Media personality", "country": "United States"},
    {"name": "Justin Bieber", "follower_count": 294, "description": "Musician", "country": "Canada"},
    {"name": "National Geographic", "follower_count": 277, "description": "Media magazine", "country": "United States"},
    {"name": "Virat Kohli", "follower_count": 273, "description": "Cricketer", "country": "India"},
    {"name": "FC Barcelona", "follower_count": 143, "description": "Football club", "country": "Spain"},
    {"name": "Drake", "follower_count": 142, "description": "Musician", "country": "United States"},
    {"name": "Ellen DeGeneres", "follower_count": 135, "description": "Comedian & TV host", "country": "United States"},
    {"name": "Kylian Mbappé", "follower_count": 126, "description": "Footballer", "country": "France"},
    {"name": "Billie Eilish", "follower_count": 124, "description": "Musician", "country": "United States"},
    {"name": "Gal Gadot", "follower_count": 107, "description": "Actress", "country": "Israel"},
    {"name": "NASA", "follower_count": 96, "description": "Space agency", "country": "United States"},
    {"name": "Nike", "follower_count": 299, "description": "Sportswear brand", "country": "United States"},
    {"name": "Kendall Jenner", "follower_count": 286, "description": "Media personality", "country": "United States"},
    {"name": "Taylor Swift", "follower_count": 282, "description": "Musician", "country": "United States"},
    {"name": "Jennifer Lopez", "follower_count": 247, "description": "Musician & actress", "country": "United States"},
    {"name": "Neymar Jr.", "follower_count": 231, "description": "Footballer", "country": "Brazil"},
    {"name": "Nicki Minaj", "follower_count": 224, "description": "Musician", "country": "Trinidad and Tobago"},
    {"name": "Kourtney Kardashian", "follower_count": 217, "description": "Media personality", "country": "United States"},
    {"name": "Miley Cyrus", "follower_count": 212, "description": "Musician & actress", "country": "United States"},
    {"name": "Katy Perry", "follower_count": 202, "description": "Musician", "country": "United States"},
    {"name": "Kevin Hart", "follower_count": 176, "description": "Comedian & actor", "country": "United States"},
    {"name": "UEFA Champions League", "follower_count": 121, "description": "Football competition", "country": "Europe"},
    {"name": "Lisa (BLACKPINK)", "follower_count": 106, "description": "Musician", "country": "South Korea"},
    {"name": "Vin Diesel", "follower_count": 103, "description": "Actor", "country": "United States"},
    {"name": "Narendra Modi", "follower_count": 97, "description": "Prime Minister of India", "country": "India"},
    {"name": "Shraddha Kapoor", "follower_count": 93, "description": "Actress", "country": "India"},
    {"name": "Shakira", "follower_count": 93, "description": "Musician", "country": "Colombia"},
    {"name": "Priyanka Chopra", "follower_count": 92, "description": "Actress", "country": "India"},
    {"name": "NBA", "follower_count": 90, "description": "Basketball league", "country": "United States"},
    {"name": "Snoop Dogg", "follower_count": 88, "description": "Musician", "country": "United States"},
    {"name": "David Beckham", "follower_count": 88, "description": "Former footballer", "country": "United Kingdom"}
]
